### PR TITLE
Getting Started

### PR DESCRIPTION
**Pull request by PrashantVaidyanathan**
This PR includes:
- A new directory structure for examples, getting started, and past workshops
- Three notebooks:
  - A Basic introduction to SBOL3 to add a component and a sequence
  - A Notebook that shows how one can use SBOL Utilities to create a transcriptional unit and converts this to an Excel file.
  - A notebook that loads a previously created SBOL3 file (again a transcriptional unit), and visualises the Transcriptional unit using Dnaplotlib and ParaSBOLv.

### CODE REVIEW

**Comment by PrashantVaidyanathan** [comment]
@tcmitchell, @jakebeal - This is in a draft stage and only has 1 notebook so far. But would love to hear your thoughts and get some feedback. Also, happy to continue this conversation in Slack first if that is easier.

**Comment by cjmyers** [comment]
This is a great effort.  Thanks for doing this.

**Review by LukasBuecherl — APPROVED** [review]
Initial content commit looks good to me.

**Review by tcmitchell — APPROVED** [review]

**Comment by tcmitchell** [comment]
@PrashantVaidyanathan This is tremendous, thanks for putting this work in!

**Review by fxbuson — APPROVED** [review]

**Pull request merged**
